apiVersion: v1
data:
  DB_ADAPTER: postgresql
  DB_DB: {{ .Values.db.database }}
  DB_HOST: {{ .Values.db.host }}
  {{- if .Values.sentry.dsn }}
  SENTRY_DSN: {{ .Values.sentry.dsn }}
  {{- end }}
  {{- if .Values.zipkin.host }}
  ZIPKIN_REPORT_HOST: {{ .Values.zipkin.host }}
  {{- end }}
kind: ConfigMap
metadata:
  name: config
