apiVersion: v1
data:
  DB_ADAPTER: postgresql
  DB_DB: {{ .Values.db.database }}
  DB_HOST: {{ .Values.db.host }}
  {{- if .Values.sentry.dsn }}
  SENTRY_DSN: {{ .Values.sentry.dsn }}
  {{- end }}
  {{- if .Values.tracing.zipkin_host }}
  OPENCENSUS_REPORT_URL: {{ template "certmanager.hostname" . }}/trace-collector/v1/trace
  OPENCENSUS_INTERNAL_REPORT_URL: http://censuscollector.{{ .Release.Namespace }}:55678/v1/trace
  {{- end }}
kind: ConfigMap
metadata:
  name: config
