apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scheduler
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - args:
        - rake
        - resque:scheduler
        env:
        - name: SECRET_KEY_BASE
          value: unused
        envFrom:
        - secretRef:
            name: sqlaccount
            optional: false
        - configMapRef:
            name: config
            optional: false
        image: ajacques/certmanager:latest
        imagePullPolicy: Always
        name: scheduler
        resources: {}
        securityContext:
          capabilities:
            add:
            - CHOWN
            drop:
            - ALL
          readOnlyRootFilesystem: true
      securityContext: {}