apiVersion: v1
data:
  DB_DB: {{ .Values.db.database | b64enc }}
  DB_USER: {{ .Values.db.username | b64enc }}
  DB_PASS: {{ .Values.db.password | b64enc }}
  SECRET_KEY_BASE: {{ .Values.security.secret_key | b64enc }}
kind: Secret
metadata:
  name: sqlaccount
type: Opaque
