apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: worker
        chart: {{ .Chart.Name }}
    spec:
      affinity: {}
      containers:
      - args:
        - rake
        - resque:work
        env:
        - name: QUEUE
          value: '*'
        - name: SECRET_KEY_BASE
          value: unused
        - name: ZIPKIN_SERVICE_NAME
          value: CertManager-Worker
        envFrom:
        - secretRef:
            name: sqlaccount
            optional: false
        - configMapRef:
            name: config
            optional: false
        image: ajacques/certmanager:latest
        imagePullPolicy: Always
        name: worker
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      securityContext: {}
