apiVersion: v1
data:
  oc-agent-config: |-
    receivers:
      opencensus:
        address: ':55678'
    exporters:
      zipkin:
        service_name: CertManager
        endpoint: {{ .Values.tracing.zipkin_host }}/api/v2/spans
        local_endpoint: {{ template "certmanager.hostname" . }}
        upload_period: 10s
kind: ConfigMap
metadata:
  name: oc-agent-conf
