apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencensusagent
spec:
  selector:
    matchLabels:
      app: censuscollector
      chart: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/census-collector/config-map.yaml") . | sha256sum }}
      labels:
        app: censuscollector
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - args:
        - --config=/conf/oc-agent-config.yaml
        image: omnition/opencensus-agent:1.0.15
        imagePullPolicy: IfNotPresent
        name: oc-agent-container
        resources:
          limits:
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /conf
          name: oc-agent-config-vol
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: oc-agent-config
            path: oc-agent-config.yaml
          name: oc-agent-conf
        name: oc-agent-config-vol
