apiVersion: v2
data:
  opendmarc.conf: |-
    AutoRestart False
    Socket inet:9998@127.0.0.1
    AuthservID OpenDMARC
    RejectFailures true
    IgnoreAuthenticatedClients true
    SPFIgnoreResults true
    SPFSelfValidate true
    PublicSuffixList /usr/share/publicsuffix/public_suffix_list.dat
kind: ConfigMap
metadata:
  name: opendmarcconf
