{{- if .Values.ingress.cache.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_cache {{ .Values.ingress.cache.nginx_cache_zone }};
      expires max;
      add_header X-Cache-Status $upstream_cache_status;
      proxy_cache_key $request_method$request_uri;
      proxy_cache_valid 200 7d;
      proxy_cache_use_stale error timeout invalid_header updating http_500 http_502 http_503 http_504;
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: sentry-assets
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: web
            port:
              number: 9000
        path: /_static
        pathType: Prefix
  {{- if ne .Values.ingress.tls_secret_source "NoTLS" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    {{- if eq .Values.ingress.tls_secret_source "ExistingSecret" }}
    secretName: {{ .Values.ingress.tls_secret_name }}
    {{- else if eq .Values.ingress.tls_secret_source "Replicated" }}
    secretName: sentry-cert
    {{- end }}
  {{- end }}
{{- end }}
