apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ui-network-policy
spec:
  podSelector:
    matchLabels:
      component: web
      chart: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - port: 9000
