apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    component: web
    release: {{ template "sentry.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
