{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: statsd-network-policy
spec:
  podSelector:
    matchLabels:
      component: statsd
      chart: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8125
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 9102
  # Our Statsd container should not connect to anything else
  egress: []
{{- end }}
