{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: statsd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '1'
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  selector:
    component: statsd
    chart: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
{{- end }}
