{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: statsd
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: statsd
spec:
  clusterIP: None
  selector:
    component: statsd
    chart: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
  ports:
  - port: 9102
    targetPort: 9102
    protocol: TCP
    name: metrics
{{- end }}
