apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beat-role-binding
subjects:
- kind: ServiceAccount
  name: beat-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: beat-role
  apiGroup: rbac.authorization.k8s.io
