apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-update.fullname" . }}-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-update.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: kube-update-service-account
  namespace: {{ .Release.Namespace }}
