apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "kube-update.name" . }}
  labels:
    app: {{ template "kube-update.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: {{ template "kube-update.name" . }}
        release: {{ .Release.Name }}
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: kube-update
              image: "ajacques/kube-update:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- if .Values.email.enabled }}
              - name: APP_EMAIL_HOST
                value: {{ .Values.email.relay.host }}
              - name: APP_EMAIL_PORT
                value: "{{ .Values.email.relay.port }}"
              - name: APP_EMAIL_TO
                value: {{ .Values.email.recipient.address }}
                {{- end }}
                {{- if .Values.sentry.dsn }}
              - name: SENTRY_DSN
                value: {{ .Values.sentry.dsn }}
                {{- end }}
              securityContext:
                capabilities:
                  drop:
                  - ALL
              terminationMessagePolicy: FallbackToLogsOnError
          serviceAccountName: kube-update-service-account
          restartPolicy: Never
          schedulerName: default-scheduler
          {{- if .Values.nodeSelector }}
          nodeSelector:
          {{ toYaml .Values.nodeSelector | indent 8 }}
          {{- end }}
