apiVersion: v1
data:
  # https://github.com/getsentry/onpremise/blob/master/install/create-kafka-topics.sh
  create-kakfa-topics.sh: |
    echo "${_group}Creating additional Kafka topics ..."

    # NOTE: This step relies on `kafka` being available from the previous `snuba-api bootstrap` step
    # XXX(BYK): We cannot use auto.create.topics as Confluence and Apache hates it now (and makes it very hard to enable)
    EXISTING_KAFKA_TOPICS=$(kafka-topics --list --bootstrap-server {{ .Values.kafka.hostname }} 2>/dev/null)
    NEEDED_KAFKA_TOPICS="ingest-attachments ingest-transactions ingest-events ingest-sessions event-replacements events transactions events-subscription-results outcomes snuba-commit-log snuba-transactions-commit-log ingest-replay-recordings processed-profiles profiles profiles-call-tree ingest-occurrences"
    for topic in $NEEDED_KAFKA_TOPICS; do
      if ! echo "$EXISTING_KAFKA_TOPICS" | grep -wq $topic; then
        kafka-topics --create --topic $topic --bootstrap-server {{ .Values.kafka.hostname }} --config retention.ms=86400000 --config segment.ms=3600000
        echo ""
      fi
    done

    kafka-consumer-groups --bootstrap-server {{ .Values.kafka.hostname }} --delete --group snuba-post-processor
kind: ConfigMap
metadata:
  name: install-files
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '0'
