apiVersion: batch/v1
kind: Job
metadata:
  name: sentry-upgrade
  labels:
    chart: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": '5'
spec:
  backoffLimit: 2
  template:
    metadata:
      name: sentry-upgrade
      labels:
        component: sentry-upgrade
        release: {{ template "sentry.fullname" . }}
    spec:
      restartPolicy: Never
      containers:
      - args:
          - upgrade
          - --noinput
          - --create-kafka-topics
        envFrom:
          - secretRef:
              name: sentry
              optional: false
          - configMapRef:
              name: sentry
              optional: false
          - configMapRef:
              name: snuba-config
              optional: false
        image: getsentry/sentry:{{ .Values.sentry.version }}
        imagePullPolicy: IfNotPresent
        name: sentry-upgrade
        volumeMounts:
          - mountPath: /var/lib/sentry/files
            name: files
          - mountPath: /etc/sentry/config.yml
            name: configyml
            readOnly: true
            subPath: config.yml
          - mountPath: /etc/sentry/sentry.conf.py
            name: configyml
            readOnly: true
            subPath: sentry.conf.py
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - CHOWN
              - SETGID
              - SETUID
            drop:
              - ALL
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
      volumes:
        - name: files
          {{- if eq .Values.persistence.type.filestore "BindMount" }}
          hostPath:
            path: {{ .Values.persistence.bind_mount.base_dir }}/filestore
            type: ""
          {{- end }}
        - configMap:
            defaultMode: 292
            name: sentryconfig
            optional: false
          name: configyml
