apiVersion: batch/v1
kind: Job
metadata:
  name: snuba-upgrade
  labels:
    chart: {{ .Chart.Name }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: 5
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: snuba-upgrade
      labels:
        component: snuba-upgrade
        release: {{ template "sentry.fullname" . }}
    spec:
      restartPolicy: Never
      containers:
      - args:
          - migrations
          - migrate
          - --force
        envFrom:
          - secretRef:
              name: sentry
              optional: false
          - configMapRef:
              name: sentry
              optional: false
          - configMapRef:
              name: snuba-config
              optional: false
        image: getsentry/snuba:{{ .Values.snuba.version }}
        imagePullPolicy: IfNotPresent
        name: snuba-upgrade
        securityContext:
          capabilities:
            add:
              - CHOWN
              - SETGID
              - SETUID
            drop:
              - ALL
        volumeMounts:
          - mountPath: /etc/sentry/config.yml
            name: configyml
            readOnly: true
            subPath: config.yml
          - mountPath: /etc/sentry/sentry.conf.py
            name: configyml
            readOnly: true
            subPath: sentry.conf.py
      volumes:
        - configMap:
            defaultMode: 292
            name: sentryconfig
            optional: false
          name: configyml
