apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: webui
        chart: {{ .Chart.Name }}
    spec:
      affinity: {}
      containers:
      - env:
        {{- if .Values.security.csp.report_uri }}
        - name: CSP_REPORT_URI
          value: {{ .Values.security.csp.report_uri }}
        {{- end }}
        - name: ZIPKIN_SAMPLE_RATE
          value: "{{ .Values.tracing.sample_rate }}"
        envFrom:
        - secretRef:
            name: sqlaccount
            optional: false
        - configMapRef:
            name: config
            optional: false
        image: ajacques/certmanager:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        name: webui
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            drop:
            - ALL
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: true
          runAsNonRoot: false
