apiVersion: v1
data:
  sentry.xml: |-
    <yandex>
    {{- if .Values.prometheus.enabled }}
      <prometheus>
        <endpoint>/metrics</endpoint>
        <port>8125</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
      </prometheus>
    {{- end }}
      <merge_tree>
        <enable_mixed_granularity_parts>1</enable_mixed_granularity_parts>
      </merge_tree>
    </yandex>
kind: ConfigMap
metadata:
  name: clickhouse-config