apiVersion: v1
data:
  sentry.xml: |-
    <yandex>
      <max_server_memory_usage_to_ram_ratio>
        <include from_env="MAX_MEMORY_USAGE_RATIO"/>
      </max_server_memory_usage_to_ram_ratio>
      <logger>
          <level>warning</level>
          <console>true</console>
      </logger>
      <query_thread_log remove="remove"/>
      <query_log remove="remove"/>
      <text_log remove="remove"/>
      <trace_log remove="remove"/>
      <metric_log remove="remove"/>
      <asynchronous_metric_log remove="remove"/>

      <!-- Update: Required for newer versions of Clickhouse -->
      <session_log remove="remove"/>
      <part_log remove="remove"/>
      <profiles>
          <default>
              <log_queries>0</log_queries>
              <log_query_threads>0</log_query_threads>
          </default>
      </profiles>
    {{- if .Values.prometheus.enabled }}
      <prometheus>
        <endpoint>/metrics</endpoint>
        <port>8125</port>
        <metrics>true</metrics>
        <events>true</events>
        <asynchronous_metrics>true</asynchronous_metrics>
      </prometheus>
    {{- end }}
      <merge_tree>
        <enable_mixed_granularity_parts>1</enable_mixed_granularity_parts>
      </merge_tree>
    </yandex>
kind: ConfigMap
metadata:
  name: clickhouse-config
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'