{{- if .Values.prometheus.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clickhouse-network-policy
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '1'
spec:
  podSelector:
    matchLabels:
      component: clickhouse
      chart: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8123 # Clickhouse HTTP
    - protocol: TCP
      port: 9000 # Clickhouse TCP Native
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 9102 # Prometheus
  # This container should not connect to anything else
  egress: []
{{- end }}
