apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.persistence.resources.requests.storage }}
  storageClassName: {{ .Values.clickhouse.persistence.storageClassName }}
