apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      component: clickhouse
      chart: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/clickhouse/config-map.yaml") . | sha256sum }}
      {{- if and .Values.prometheus.enabled (not .Values.prometheus.use_crds) }}
        prometheus.io/port: '8125'
        prometheus.io/scrape: 'true'
      {{- end }}
      labels:
        component: clickhouse
        chart: {{ .Chart.Name }}
    spec:
    {{- if .Values.clickhouse.affinity }}
      affinity: {{ toYaml .Values.clickhouse.affinity | nindent 8 }}
    {{- end }}
      containers:
      - image: altinity/clickhouse-server:23.8.11.29.altinitystable
        imagePullPolicy: IfNotPresent
        name: clickhouse
        env:
          - name: MAX_MEMORY_USAGE_RATIO
            value: '0.3'
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: datavol
        - mountPath: /etc/clickhouse-server/config.d/sentry.xml
          name: config
          readOnly: true
          subPath: sentry.xml
      volumes:
      - name: datavol
        {{- if eq .Values.persistence.type.storage "BindMount" }}
        hostPath:
          path: {{ .Values.persistence.bind_mount.base_dir }}/clickhouse
          type: DirectoryOrCreate
        {{- end }}
      - configMap:
          defaultMode: 292
          name: clickhouse-config
          optional: false
        name: config
