apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      component: clickhouse
      chart: {{ .Chart.Name }}
  template:
    metadata:
      {{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io/port: '9102'
        prometheus.io/scrape: 'true'
      {{- end }}
      labels:
        component: clickhouse
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - image: yandex/clickhouse-server:20.3.9.70
        imagePullPolicy: IfNotPresent
        name: clickhouse
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: datavol
        - mountPath: /etc/clickhouse-server/config.d/sentry.xml
          name: config
          readOnly: true
          subPath: sentry.xml
      volumes:
      - name: datavol
        {{- if eq .Values.persistence.type.storage "BindMount" }}
        hostPath:
          path: {{ .Values.persistence.bind_mount.base_dir }}/clickhouse
          type: DirectoryOrCreate
        {{- end }}
      - configMap:
          defaultMode: 292
          name: clickhouse-config
          optional: false
        name: config
