apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      component: memcached
      chart: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        net.technowizardry.upgrade/version-match: '{version}-alpine'
        match-regex.version-checker.io/memcached: '^\d+\.\d+\.\d+-alpine'
{{- if and .Values.prometheus.enabled (not .Values.prometheus.use_crds) }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9150'
{{- end }}
      labels:
        component: memcached
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - args:
        - memcached
        - -m
        - "128"
        image: memcached:1.6.21-alpine
        imagePullPolicy: IfNotPresent
        name: memcached
        resources:
          limits:
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 11211
{{- if .Values.prometheus.enabled }}
      - image: quay.io/prometheus/memcached-exporter:v0.9.0
        imagePullPolicy: IfNotPresent
        name: metrics
        ports:
        - containerPort: 9150
          name: metrics
          protocol: TCP
{{- end }}
