apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: memcached-network-policy
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'
spec:
  podSelector:
    matchLabels:
      component: memcached
      chart: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 11211
{{- if .Values.prometheus.enabled }}
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 9150
{{- end }}
  # Our Memcached container should not connect to anything else
  egress: []
