apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: openzipkin-dependencies
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - env:
            - name: STORAGE_TYPE
            {{- if eq .Values.db.type "MySQL" }}
              value: mysql
            - name: MYSQL_HOST
              value: {{ .Values.db.host }}
            envFrom:
              - secretRef:
                  name: credentials
                  optional: false
            {{- else if eq .Values.db.type "Elasticsearch" }}
              value: elasticsearch
            - name: ES_HOSTS
              value: {{ .Values.db.host }}
            {{- end }}
            image: openzipkin/zipkin-dependencies:2.4.1
            name: dependencies
  schedule: 0 * * * *
