apiVersion: apps/v1
kind: Deployment
metadata:
  name: openzipkin
spec:
  selector:
    matchLabels:
      app: backend
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: backend
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - env:
        - name: STORAGE_TYPE
        {{- if eq .Values.db.type "MySQL" }}
          value: mysql
        - name: MYSQL_HOST
          value: {{ .Values.db.host }}
        envFrom:
          - secretRef:
              name: credentials
              optional: false
        {{- else if eq .Values.db.type "Elasticsearch" }}
          value: elasticsearch
        - name: ES_HOSTS
          value: {{ .Values.db.host }}
        {{- end }}
        image: openzipkin/zipkin:2.21.6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 9411
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
        name: openzipkin
