{{- if eq .Values.db.type "Mysql" }}
apiVersion: v1
data:
  MYSQL_DB: {{ .Values.db.database | b64enc }}
  MYSQL_USER: {{ .Values.db.username | b64enc }}
  MYSQL_PASS: {{ .Values.db.password | b64enc }}
kind: Secret
metadata:
  name: credentials
type: Opaque
{{- end }}