apiVersion: v1
kind: Service
metadata:
  name: openzipkin-backend
spec:
  ports:
  - name: web
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: backend
    chart: {{ .Chart.Name }}
