apiVersion: v1
data:
  {{- if .Values.jails.ssh }}
  sshd.conf: |-
    [sshd]
    enabled = true
    port = ssh
    filter = sshd[mode=aggressive]
    logpath = /host/var/log/auth.log
    maxretry = 5
  {{- end }}
  {{- if .Values.jails.dovecot }}
  dovecot.conf: |-
    [dovecot]
    enabled = true
    filter = dovecot
    action = iptables-multiport[name=dovecot-pop3imap, port="pop3,imap", protocol=tcp]
    logpath = /host/var/log/mail.log
  {{- end }}
kind: ConfigMap
metadata:
  name: jails
