apiVersion: v1
data:
  {{- if .Values.jailsd.ssh }}
  sshd.conf: |-
    [sshd]
    enabled = true
    port = ssh
    filter = sshd[mode=aggressive]
    logpath = /host/var/log/auth.log
    maxretry = 5
  {{- end }}
  {{- if .Values.jailsd.dovecot }}
  dovecot.conf: |-
    [dovecot-pop3imap]
    enabled = true
    filter = dovecot-pop3imap
    action = iptables-multiport[name=dovecot-pop3imap, port="pop3,imap", protocol=tcp]
    logpath = /var/log/maillog
    maxretry = 20
    findtime = 1200
    bantime = 1200
  {{- end }}
kind: ConfigMap
metadata:
  name: jails
