apiVersion: v1
data:
  config.yml: |
    relay:
      upstream: http://web.{{ .Release.Namespace }}.svc.cluster.local.:9000/
      host: 0.0.0.0
      port: 3000
    logging:
     level: WARN
    processing:
      enabled: true
      kafka_config:
        - name: bootstrap.servers
          value: {{ .Values.kafka.hostname | quote }}
        - name: message.max.bytes
          value: 50000000 # 50MB
      redis: redis://redis.{{ .Release.Namespace }}.svc.cluster.local.:6379
    health:
      max_memory_percent: 1.0
    spool:
      envelopes:
        path: "/tmp/relay-spool-envelopes"
        max_backpressure_memory_percent: 1.0

kind: ConfigMap
metadata:
  name: relay-config
