apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: relay
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: relay
          servicePort: 3000
        path: /api/store
      - backend:
          serviceName: relay
          servicePort: 3000
        path: ^/api/[1-9]\d*/
  {{- if .Values.ingress.tls_secret_name }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls_secret_name }}
  {{- end }}
