apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relay
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          name: relay
          port:
            number: 3000
        path: /api/store
        pathType: Exact
      - backend:
          serviceName: relay
          servicePort: 3000
        path: /api/[1-9]+/.*$
        pathType: ImplementationSpecific
  {{- if ne .Values.ingress.tls_secret_source "NoTLS" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    {{- if eq .Values.ingress.tls_secret_source "ExistingSecret" }}
    secretName: {{ .Values.ingress.tls_secret_name }}
    {{- else if eq .Values.ingress.tls_secret_source "Replicated" }}
    secretName: sentry-cert
    {{- end }}
  {{- end }}
