apiVersion: v1
data:
  credentials.json: {{ printf "{'public_key':'%s','private_key':'%s','id':'1466ec20-f42f-4358-8842-4566ca656ec7'" .Values.relay.public_key .Values.relay_private_key | b64enc }}
kind: Secret
metadata:
  name: relay-secret
type: Opaque
