apiVersion: v1
data:
  oc-agent-config: |-
    receivers:
      opencensus:
        address: '127.0.0.1:55678'
    exporters:
      {{- if eq .Values.tracing.type "OpenCensus" }}
      opencensus:
        endpoint: {{ .Values.tracing.opencensus_collector | quote }}
        upload_period: 10s
      {{- else if eq .Values.tracing.type "OpenZipkin" }}
      zipkin:
        endpoint: {{ printf "%s/api/v2/spans" .Values.tracing.openzipkin_endpoint | quote }}
        upload_period: 10s
      {{- end }}
kind: ConfigMap
metadata:
  name: oc-agent-conf
