apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: redis
spec:
  clusterIP: None
  selector:
    component: redis
    chart: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: metrics
