apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: '1'
    match-regex.version-checker.io/redis: ^v\d+\.\d+\.\d+-alpine$
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      component: redis
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        component: redis
        chart: {{ .Chart.Name }}
{{- if .Values.prometheus.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
{{- end }}
    spec:
      containers:
      - image: redis:6.2.5
        imagePullPolicy: IfNotPresent
        name: redis
        volumeMounts:
        - mountPath: /data
          name: datavol
{{- if .Values.prometheus.enabled }}
      - name: prometheus-exporter
        env:
        - name: REDIS_ADDR
          value: '127.0.0.1'
        - name: REDIS_EXPORTER_REDIS_ONLY_METRICS
          value: 'true'
        image: oliver006/redis_exporter:v1.27.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9121
          name: exporter-port
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: exporter-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
{{- end }}
      volumes:
      - name: datavol
        {{- if eq .Values.persistence.type.storage "BindMount" }}
        hostPath:
          path: {{ .Values.persistence.bind_mount.base_dir }}/redis
          type: ""
        {{- end }}
