apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.ui.annotations | indent 4 }}
  name: openzipkin-ui
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: openzipkin-backend
          servicePort: 9411
        pathType: Prefix
        path: '/'
  {{- if ne .Values.ingress.tls_secret_source "NoTLS" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    {{- if eq .Values.ingress.tls_secret_source "ExistingSecret" }}
    secretName: {{ .Values.ingress.tls_secret_name }}
    {{- else if eq .Values.ingress.tls_secret_source "Replicated" }}
    secretName: replicated-cert
    {{- end }}
  {{- end }}
