apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.ui.annotations | indent 4 }}
  name: openzipkin-ui
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: openzipkin-backend
          servicePort: 9411
        pathType: Prefix
        path: '/'
  {{- if .Values.ingress.tls_secret_name }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls_secret_name }}
  {{- end }}
