apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: vouchservice
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vouchproxy
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: vouchproxy
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - image: voucher/vouch-proxy:0.6.4
        imagePullPolicy: Always
        name: vouchproxy
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /config/
          name: config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 292
          name: vouchconfig
          optional: false
        name: config

