apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
spec:
  podSelector:
    matchLabels:
      chart: {{ .Chart.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      # Granted because NGINX runs on the hostNetwork
        - ipBlock:
            cidr: 0.0.0.0/0
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 9090
  egress:
    # Permit DNS
    - ports:
      - port: 53
        protocol: UDP
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    # Permit outbound traffic for OAuth
    - ports:
        - port: 443
          protocol: TCP
