{{- if .Values.ingress.tls_replicate }}
apiVersion: v1
data:
  ca.crt: ''
  tls.crt: ''
  tls.key: ''
kind: Secret
metadata:
  annotations:
   replicator.v1.mittwald.de/replicate-from: {{ .Values.ingress.tls_replicate_from }}
   # Force the replicator to always update it. This seems to be needed because the data block will be updated, but the old annotation
   # won't be updated.
   replicator.v1.mittwald.de/replicated-from-version: '0'
  name: {{ .Values.ingress.tls_secret_name }}
type: kubernetes.io/tls
{{- end }}