{{- if .Values.ingress.tls_replicate }}
apiVersion: v1
data:
  ca.crt: ''
  tls.crt: ''
  tls.key: ''
kind: Secret
metadata:
  annotations:
   replicator.v1.mittwald.de/replicate-from: {{ .Values.ingress.tls_replicate_from }}
  name: {{ .Values.ingress.tls_secret_name }}
type: kubernetes.io/tls
{{- end }}