apiVersion: v1
kind: Service
metadata:
  name: vouchproxy
  labels:
    app: vouchproxy
    chart: {{ .Chart.Name }}
spec:
  clusterIP: None
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: vouchproxy
    chart: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
