apiVersion: v1
data:
  {{- if .Values.jailsd.ssh }}
  sshd.conf: |-
    [sshd]
    enabled = true
    port = ssh
    filter = sshd[mode=aggressive]
    logpath = /host/var/log/auth.log
    maxretry = 5
  {{- end }}
kind: ConfigMap
metadata:
  name: jails
