apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dovecot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dovecot
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app: dovecot
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - args:
        - -c
        - /etc/dovecot/dovecot.conf
        - -F
        command:
        - /usr/sbin/dovecot
        image: ajacques/kube-mail:latest
        imagePullPolicy: Always
        name: dovecot
        ports:
        - containerPort: 143
          hostPort: 143
          name: 8143tcp143
          protocol: TCP
        - containerPort: 110
          hostPort: 110
          name: 110tcp110
          protocol: TCP
        - containerPort: 993
          hostPort: 993
          name: 993tcp993
          protocol: TCP
        - containerPort: 995
          hostPort: 995
          name: 995tcp995
          protocol: TCP
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/dovecot
          name: mail
        - mountPath: /etc/dovecot/conf.d
          name: config
          readOnly: true
        - mountPath: /var/spool/postfix/private/
          name: postfix
        - mountPath: /etc/dovecot/ssl/
          name: mailcert
          readOnly: true
      volumes:
      - hostPath:
          path: /var/dovecot
          type: ""
        name: mail
      - configMap:
          defaultMode: 292
          name: dovecot
          optional: false
        name: config
      - hostPath:
          path: /var/spool/postfix/private/
          type: ""
        name: postfix
      - name: mailcert
        secret:
          defaultMode: 292
          optional: false
          secretName: mail
