apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dovecot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: dovecot
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: dovecot
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - args:
        - -c
        - /etc/dovecot/dovecot.conf
        - -F
        command:
        - /usr/sbin/dovecot
        image: ajacques/kube-mail:latest
        imagePullPolicy: Always
        name: dovecot
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/dovecot
          name: mail
        - mountPath: /etc/dovecot/conf.d
          name: config
          readOnly: true
        - mountPath: /var/spool/postfix/private/
          name: postfix
        - mountPath: /etc/dovecot/ssl
          name: mailcert
          readOnly: true
      volumes:
      - hostPath:
          path: /var/dovecot
          type: ""
        name: mail
      - configMap:
          defaultMode: 292
          name: dovecot
          optional: false
        name: config
      - hostPath:
          path: /var/spool/postfix/private/
          type: ""
        name: postfix
      - name: mailcert
        secret:
          defaultMode: 292
          optional: false
          secretName: mail
