apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      component: cron
      release: {{ template "sentry.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config2: {{ include (print $.Template.BasePath "/sentry-config-file.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        component: cron
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - args:
        - run
        - cron
        envFrom:
        - secretRef:
            name: sentry
            optional: false
        - configMapRef:
            name: sentry
            optional: false
        - configMapRef:
            name: snuba-config
            optional: false
        image: getsentry/sentry:{{ .Values.sentry.version }}
        imagePullPolicy: IfNotPresent
        name: cron
        resources:
          requests:
            memory: 300Mi
          limits:
            memory: 300Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        volumeMounts:
          - mountPath: /var/lib/sentry/files
            name: files
          - mountPath: /etc/sentry/config.yml
            name: configyml
            readOnly: true
            subPath: config.yml
          - mountPath: /etc/sentry/sentry.conf.py
            name: configyml
            readOnly: true
            subPath: sentry.conf.py
      volumes:
        - name: files
          emptyDir: {}
        - configMap:
            defaultMode: 292
            name: sentryconfig
            optional: false
          name: configyml
