apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cron
  labels:
    app: {{ template "sentry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      component: cron
      release: {{ template "sentry.fullname" . }}
  template:
    metadata:
      labels:
        component: cron
        release: {{ template "sentry.fullname" . }}
    spec:
      affinity: {}
      containers:
      - args:
        - run
        - cron
        envFrom:
        - secretRef:
            name: sentry
            optional: false
        - configMapRef:
            name: sentry
            optional: false
        image: sentry:9.0.0
        imagePullPolicy: Always
        name: cron
        resources:
          limits:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
