apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
spec:
  podSelector:
    matchLabels:
      chart: {{ .Chart.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
