apiVersion: v1
data:
  {{- if .Values.github.enabled }}
  GITHUB_APP_ID: {{ .Values.github.api.id | b64enc }}
  GITHUB_API_SECRET: {{ .Values.github.api.secret | b64enc }}
  {{- end }}
  SENTRY_DB_USER: {{ .Values.db.username | b64enc }}
  SENTRY_DB_PASSWORD: {{ .Values.db.password | b64enc }}
  SENTRY_SECRET_KEY: {{ .Values.sentry.secret_key | b64enc }}
kind: Secret
metadata:
  name: sentry
type: Opaque
