apiVersion: v1
data:
  SENTRY_DB_USER: {{ .Values.db.username | b64enc }}
  SENTRY_DB_PASSWORD: {{ .Values.db.password | b64enc }}
  SENTRY_SECRET_KEY: {{ .Values.sentry.secret_key | b64enc }}
kind: Secret
metadata:
  name: sentry
type: Opaque
