apiVersion: v1
data:
  # /etc/sentry/config.yml
  config.yml: |
    github-app.id: {{ .Values.github.app.id }}
    github.name: '{{ .Values.github.app.name }}'
    github-app.webhook-secret: '{{ .Values.github.webhook_secret }}'
    github-app.client-id: '{{ .Values.github.app.client_id }}'
    github-app.client-secret: '{{ .Values.github.app.client_secret }}'
    github-app.private-key:
      {{ .Values.github.app.private_key | indent 6 }}
kind: ConfigMap
metadata:
  name: sentryconfig
