apiVersion: v1
kind: ConfigMap
metadata:
  name: auditbeat-config
data:
  auditbeat.yml: |-
    setup:
      kibana.host: kibana-kibana.elasticsearch.svc.cluster.local
      dashboards.enabled: true
      template:
        name: auditbeat
        pattern: auditbeat-*
        enabled: true

    auditbeat.modules:
      - audit_rules: |
          # Things that affect identity.
          -w /etc/group -p wa -k identity
          -w /etc/passwd -p wa -k identity
          -w /etc/gshadow -p wa -k identity
          -w /etc/shadow -p wa -k identity
          # Unauthorized access attempts to files (unsuccessful).
          -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -F key=access
          -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -F key=access
          -a always,exit -F arch=b64 -S open,truncate,ftruncate,creat,openat,open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -F key=access
          -a always,exit -F arch=b64 -S open,truncate,ftruncate,creat,openat,open_by_handle_at -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -F key=access
          ## for development
          # failure_mode: log
          # include_raw_message: true
          # include_warnings: true
        backlog_limit: 8196
        module: auditd
        rate_limit: 0
      - module: file_integrity
        paths:
        - /bin
        - /usr/bin
        - /sbin
        - /usr/sbin
        - /etc
    processors:
      - add_cloud_metadata:
      - add_kubernetes_metadata:
          host: ${HOSTNAME}
          indexers:
          - ip_port:
          matchers:
          - field_format:
              format: '%{[ip]}:%{[port]}'
{{ toYaml .Values.config | indent 4 }}
