apiVersion: apps/v1
kind: DaemonSet
metadata:
  generation: 12
  labels:
    app: auditbeat
    chart: auditbeat-1.1.0
    heritage: Tiller
    io.cattle.field/appId: auditbeat
    release: auditbeat
  name: auditbeat
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: auditbeat
      chart: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: auditbeat
        chart: {{ .Chart.Name }}
      containers:
      - args:
        - -e
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.elastic.co/beats/auditbeat:7.3.1
        imagePullPolicy: IfNotPresent
        name: auditbeat
        resources: {}
        securityContext:
          capabilities:
            add:
            - AUDIT_CONTROL
          runAsUser: 0
        volumeMounts:
        - mountPath: /usr/share/auditbeat/auditbeat.yml
          name: config
          readOnly: true
          subPath: auditbeat.yml
        - mountPath: /usr/share/auditbeat/data
          name: data
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: beat-service-account
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: auditbeat-config
      - name: data
        hostPath:
          path: /var/lib/auditbeat
          type: DirectoryOrCreate
