apiVersion: apps/v1
kind: Deployment
metadata:
  name: snuba-api
spec:
  selector:
    matchLabels:
      component: snuba-api
      chart: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config2: {{ include (print $.Template.BasePath "/sentry-config-file.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        component: snuba-api
        chart: {{ .Chart.Name }}
    spec:
      containers:
      # Snuba doesn't tag versions meaningfully, so we freeze ourselves
      - image: getsentry/snuba:{{ .Values.snuba.version }}
        imagePullPolicy: Always
        name: snuba
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: REDIS_HOST
          value: redis.{{ .Release.Namespace }}.svc.cluster.local.
        - name: UWSGI_MAX_REQUESTS
          value: '10000'
        - name: UWSGI_DISABLE_LOGGING
          value: 'true'
        - name: UWSGI_ENABLE_THREADS
          value: 'true'
        - name: UWSGI_DIE_ON_TERM
          value: 'true'
        - name: UWSGI_NEED_APP
          value: 'true'
        - name: UWSGI_IGNORE_SIGPIPE
          value: 'true'
        - name: UWSGI_IGNORE_WRITE_ERRORS
          value: 'true'
        - name: UWSGI_DISABLE_WRITE_EXCEPTION
          value: 'true'
        - name: DEFAULT_BROKERS
          value: kafka.kafka.svc.cluster.local.:9092
        securityContext:
          capabilities:
            add:
            - SETUID
            - SETGID
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/sentry/config.yml
          name: configyml
          readOnly: true
          subPath: config.yml
        - mountPath: /etc/sentry/sentry.conf.py
          name: configyml
          readOnly: true
          subPath: sentry.conf.py
      volumes:
      - configMap:
          defaultMode: 292
          name: sentryconfig
          optional: false
        name: configyml
