apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: snuba-cleanup
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        component: cleanup
        release: sentry-sentry
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - args:
            - cleanup
            - --dry-run
            - "False"
            envFrom:
            - secretRef:
                name: sentry
                optional: false
            - configMapRef:
                name: sentry
                optional: false
            image: getsentry/snuba:{{ .Values.snuba.version }}
            imagePullPolicy: Always
            name: cleanup
            securityContext:
              capabilities:
                drop:
                - ALL
          restartPolicy: Never
  schedule: 5 0 * * *
