apiVersion: apps/v1
kind: Deployment
metadata:
  name: snuba-outcomes-consumer
spec:
  selector:
    matchLabels:
      component: snuba-outcomes-consumer
      chart: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config2: {{ include (print $.Template.BasePath "/sentry-config-file.yaml") . | sha256sum }}
        checksum/config3: {{ include (print $.Template.BasePath "/snuba/snuba-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        component: snuba-outcomes-consumer
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - args:
        - consumer
        - --storage=outcomes_raw
        - --auto-offset-reset=earliest
        - --max-batch-time-ms=750
        envFrom:
        - secretRef:
            name: sentry
            optional: false
        - configMapRef:
            name: sentry
            optional: false
        - configMapRef:
            name: snuba-config
            optional: false
        image: getsentry/snuba:{{ .Values.snuba.version }}
        imagePullPolicy: IfNotPresent
        name: snuba-outcomes-consumer
        securityContext:
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/sentry/config.yml
          name: configyml
          readOnly: true
          subPath: config.yml
        - mountPath: /etc/sentry/sentry.conf.py
          name: configyml
          readOnly: true
          subPath: sentry.conf.py
      volumes:
      - configMap:
          defaultMode: 292
          name: sentryconfig
          optional: false
        name: configyml
