apiVersion: v1
data:
  CLICKHOUSE_HOST: clickhouse.{{ .Release.Namespace }}.svc.cluster.local.
  REDIS_HOST: redis.{{ .Release.Namespace }}.svc.cluster.local.
  DEFAULT_BROKERS: {{ .Values.kafka.hostname }}
  SNUBA_SETTINGS: docker
kind: ConfigMap
metadata:
  name: snuba-config
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: '0'
