apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: snuba-cleanup
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        component: cleanup
        release: sentry-sentry
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - args:
            - cleanup
            - --storage
            - errors
            - --dry-run
            - "False"
            envFrom:
            - secretRef:
                name: sentry
                optional: false
            - configMapRef:
                name: sentry
                optional: false
            - configMapRef:
                name: snuba-config
                optional: false
            image: getsentry/snuba:{{ .Values.snuba.version }}
            imagePullPolicy: IfNotPresent
            name: cleanup
            securityContext:
              capabilities:
                add:
                - SETGID
                - SETUID
                drop:
                - ALL
            volumeMounts:
              - mountPath: /etc/sentry/config.yml
                name: configyml
                readOnly: true
                subPath: config.yml
              - mountPath: /etc/sentry/sentry.conf.py
                name: configyml
                readOnly: true
                subPath: sentry.conf.py
          restartPolicy: Never
          volumes:
          - configMap:
              defaultMode: 292
              name: sentryconfig
              optional: false
            name: configyml
  schedule: "*/5 * * * *"
