apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
        chart: {{ .Chart.Name }}
    spec:
      affinity: {}
      containers:
      - name: appserver
        env:
        - name: ELASTICSEARCH_URL
          value: {{ .Values.elasticsearch.url }}
        {{- if .Values.sentry.dsn }}
          name: SENTRY_DSN
          value: {{ .Values.sentry.dsn }}
        {{- end }}
        image: natlas/server:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - CHGRP
            - SETUID
            - SETGID
            drop:
            - ALL
