apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
        chart: {{ .Chart.Name }}
    spec:
      initContainers:
      - args:
        - /bin/false
        image: natlas/server:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: chmod
        volumeMounts:
        - mountPath: /data
          name: datavol
      containers:
      - name: appserver
        env:
        - name: ELASTICSEARCH_URL
          value: {{ .Values.elasticsearch.url }}
        {{- if .Values.sentry.dsn.server }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn.server }}
        {{- end }}
        {{- if not (eq .Values.tracing.type "None") }}
        - name: OPENCENSUS_ENABLE
          value: 'true'
        - name: OPENCENSUS_SAMPLE_RATE
          value: {{ div .Values.tracing.sample_rate 100.0 | quote }}
        {{- end }}
        image: natlas/server:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsUser: 33 # www-data
        volumeMounts:
        - mountPath: /data
          name: datavol
      {{- if not (eq .Values.tracing.type "None") }}
      - args:
        - --config=/conf/oc-agent-config.yaml
        image: omnition/opencensus-agent:1.0.15
        imagePullPolicy: IfNotPresent
        name: oc-agent-container
        resources:
          limits:
            memory: 64Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /conf
          name: oc-agent-config-vol
          readOnly: true
      {{- end }}
      volumes:
      - name: datavol
        {{- if eq .Values.persistence.type "BindMount" }}
        hostPath:
          path: {{ .Values.persistence.bind_mount.base_dir }}/server
          type: ""
        {{- else if eq .Values.persistence.type "PersistentVolumeClaim" }}
        persistentVolumeClaim:
          claimName: serverdatapvc
        {{- else }}
        # Probably should do something here
        {{- end }}
      - configMap:
          defaultMode: 420
          items:
          - key: oc-agent-config
            path: oc-agent-config.yaml
          name: oc-agent-conf
        name: oc-agent-config-vol
