apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
        chart: {{ .Chart.Name }}
    spec:
      affinity: {}
      containers:
      - name: appserver
        env:
        - name: ELASTICSEARCH_URL
          value: {{ .Values.elasticsearch.url }}
        {{- if .Values.sentry.dsn.server }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn.server }}
        {{- end }}
        image: natlas/server:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: datavol
      volumes:
      - name: datavol
        {{- if eq .Values.persistence.type "BindMount" }}
        hostPath:
          path: {{ .Values.persistence.bind_mount.base_dir }}/server
          type: ""
        {{- else if eq .Values.persistence.type "PersistentVolumeClaim" }}
        persistentVolumeClaim:
          claimName: serverdatapvc
        {{- else }}

        {{- end }}
