apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: server
        chart: {{ .Chart.Name }}
    spec:
      initContainers:
      - args:
        - /bin/false
        image: natlas/server:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        name: chmod
        volumeMounts:
        - mountPath: /data
          name: datavol
      containers:
      - name: appserver
        env:
        - name: ELASTICSEARCH_URL
          value: {{ .Values.elasticsearch.url }}
        {{- if .Values.sentry.dsn.server }}
        - name: SENTRY_DSN
          value: {{ .Values.sentry.dsn.server }}
        {{- end }}
        image: natlas/server:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsUser: 33 # www-data
        volumeMounts:
        - mountPath: /data
          name: datavol
      volumes:
      - name: datavol
        {{- if eq .Values.persistence.type "BindMount" }}
        hostPath:
          path: {{ .Values.persistence.bind_mount.base_dir }}/server
          type: ""
        {{- else if eq .Values.persistence.type "PersistentVolumeClaim" }}
        persistentVolumeClaim:
          claimName: serverdatapvc
        {{- else }}
        # Probably should do something here
        {{- end }}
