apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server
  labels:
    app: {{ template "natlas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: server
          servicePort: 5000
        path: /
        pathType: Prefix
  {{- if ne .Values.ingress.tls_secret_source "NoTLS" }}
  tls:
  - hosts:
    - {{ .Values.ingress.hostname }}
    {{- if eq .Values.ingress.tls_secret_source "ExistingSecret" }}
    secretName: {{ .Values.ingress.tls_secret_name }}
    {{- else if eq .Values.ingress.tls_secret_source "Replicated" }}
    secretName: cert
    {{- end }}
  {{- end }}
