{{- if eq .Values.persistence.type "PersistentVolumeClaim" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: serverdatapvc
spec:
  accessModes:
  - ReadWriteMany
  annotations:
  {{- if .Values.persistence.pvc.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.pvc.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size | quote }}
{{- end }}
