apiVersion: v1
data:
  {{- if eq .Values.db.type "SQLite" }}
  SQLALCHEMY_DATABASE_URI: {{ printf "sqlite:////data/db/metadata.db" | b64enc }}
  {{- else if eq .Values.db.type "MySQL" }}
  SQLALCHEMY_DATABASE_URI: {{ printf "mysql://%s:%s@%s/%s" .Values.db.username .Values.db.password .Values.db.hostname .Values.db.database | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: credentials
type: Opaque
