apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: {{ template "natlas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: server
    chart: {{ .Chart.Name }}
  sessionAffinity: None
  type: ClusterIP
