apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
      chart: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: assets
        chart: {{ .Chart.Name }}
    spec:
      affinity: {}
      containers:
      - image: ajacques/certmanagerassets:latest
        imagePullPolicy: Always
        name: assets
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
