apiVersion: v1
kind: Service
metadata:
  name: assets
  labels:
    app: {{ template "certmanager.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: assets
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  sessionAffinity: None
  type: ClusterIP
