apiVersion: v1
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "config/config/*.conf" }}
  {{ base $path }}: {{ $root.Files.Get $path | quote }}
  {{- end }}
  '80-output.conf': 'output { elasticsearch { hosts => ["{{ .Values.elasticsearch.host }}"] index => "{{ .Values.elasticsearch.index }}" } }'
kind: ConfigMap
metadata:
  name: logstashconfig
