apiVersion: v1
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "config/config/*.conf" }}
  {{ base $path }}: {{ $root.Files.Get $path | quote }}
  {{- end }}
  {{- range $path, $bytes := .Files.Glob "config/grok/*.grok" }}
  {{ base $path }}: {{ $root.Files.Get $path | quote }}
  {{- end }}
  80-output.conf: 'output { elasticsearch { hosts => ["{{ .Values.elasticsearch.host }}"] index => "{{ .Values.elasticsearch.index }}" } }'

  # config/pipelines.yml
  pipelines.yml: '- pipeline.id: main\r\npath.config: "/usr/share/logstash/pipeline"'
  # config/logstash.yml
  logstash.yml: "http.host: \"0.0.0.0\"\r\nxpack.monitoring.elasticsearch.hosts:\r\n- \"{{ .Values.elasticsearch.host }}\""
kind: ConfigMap
metadata:
  name: logstashconfig
