apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: packetbeat-dynamic
subjects:
- kind: ServiceAccount
  name: packetbeat-dynamic
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: packetbeat-role
  apiGroup: rbac.authorization.k8s.io